version: '3.8'

services:
  spring-boot-app:
    build:
      context: .
      dockerfile: dockerfile
    image: ${DOCKER_IMAGE_NAME}
    container_name: ${DOCKER_CONTAINER_NAME}
    ports:
      - "8443:8443"
    volumes:
      - /etc/letsencrypt/keystore.p12:/etc/letsencrypt/keystore.p12
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
